services:

  mqtt:
    image: eclipse-mosquitto:2
    container_name: fleet-mqtt
    ports:
      - "${MQTT_PORT}:${MQTT_PORT}"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - fleet-network

  postgres:
    image: postgres:15
    container_name: fleet-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fleet-network

  consumer:
    build: ./backend/consumer
    container_name: fleet-consumer
    depends_on:
      - postgres
      - mqtt
    environment:
      MQTT_BROKER: mqtt
      MQTT_PORT: ${MQTT_PORT}
      MQTT_SUBSCRIBE_TOPIC: ${MQTT_SUBSCRIBE_TOPIC}
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - fleet-network
    restart: always

  simulator:
    build: ./simulator
    container_name: fleet-simulator
    depends_on:
      - mqtt
    environment:
      MQTT_BROKER: mqtt
      MQTT_PORT: ${MQTT_PORT}
      MQTT_BASE_TOPIC: ${MQTT_BASE_TOPIC}
    networks:
      - fleet-network
    restart: unless-stopped

  api:
    build: ./backend/api
    container_name: fleet-api
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      API_USERNAME: ${API_USERNAME}
      API_PASSWORD: ${API_PASSWORD}
    ports:
      - "8000:8000"
    networks:
      - fleet-network

networks:
  fleet-network:
    driver: bridge

volumes:
  postgres-data: